# Generated by Django 4.0.10 on 2023-08-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisment',
            old_name='desctiption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='auction',
            field=models.BooleanField(help_text='отметьте, если торг уместен.', verbose_name='торг'),
        ),
    ]
