# Generated by Django 4.0.10 on 2023-08-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisments', '0002_rename_desctiption_advertisment_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisment',
            table='advertisment',
        ),
    ]
