# Generated by Django 4.0.10 on 2023-08-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisments', '0003_alter_advertisment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisment',
            table='advertisments',
        ),
    ]
