# Generated by Django 4.0.10 on 2023-08-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisments', '0004_alter_advertisment_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisment',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='auction',
            field=models.BooleanField(default=False, help_text='Возможен торг или нет', verbose_name='торг'),
        ),
    ]
