# Generated by Django 4.0.10 on 2023-08-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisments', '0006_advertisment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='image',
            field=models.ImageField(default='', upload_to='advertisments/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
